"""
Feedback Routes
CRUD operations for customer feedback.
- Sentiment is AUTO-DETECTED by Gemini (no manual input needed)
- POST /feedback only requires: text, customer_id, product_id, source, rating, category
- sentiment_respon is generated by Gemini using RAG context (similar past feedbacks)
"""

import logging
from typing import List, Optional
from datetime import datetime, timedelta
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import select, func, desc
from sqlalchemy.ext.asyncio import AsyncSession
from pydantic import BaseModel
from backend.database import get_db
from backend.models import Feedback, SentimentType
from backend.rag_pipeline import get_rag_pipeline
from backend.gemini_service import get_gemini_service

logger = logging.getLogger(__name__)
router = APIRouter()


# ---------------------------------------------------------------------------
# Request / Response Models
# ---------------------------------------------------------------------------

class FeedbackCreate(BaseModel):
    """
    Create feedback request.
    Gemini auto-detects: sentiment and sentiment_respon (via RAG context).
    Category is user-provided.
    """
    text: str
    customer_id: Optional[str] = None
    product_id: Optional[str] = None
    source: str = "web"
    rating: Optional[int] = None
    category: Optional[str] = None

    class Config:
        json_schema_extra = {
            "example": {
                "text": "Pengiriman sangat lambat dan barang datang dalam kondisi rusak",
                "customer_id": "cust_123",
                "product_id": "prod_456",
                "source": "website",
                "rating": 2,
                "category": "delivery"
            }
        }


class FeedbackUpdate(BaseModel):
    """Update feedback request"""
    text: Optional[str] = None
    category: Optional[str] = None
    rating: Optional[int] = None
    is_verified: Optional[bool] = None


class FeedbackResponse(BaseModel):
    """
    Feedback response model.

    Auto-detected fields dari Gemini (with RAG context):
    - sentiment       → positive / neutral / negative
    - sentiment_respon → personalized response generated by Gemini

    User-provided fields:
    - category  → diisi saat submit feedback
    """
    id: int
    text: str
    customer_id: Optional[str]
    product_id: Optional[str]
    sentiment: str
    sentiment_respon: Optional[str]
    category: Optional[str]
    rating: Optional[int]
    source: Optional[str]
    created_at: datetime

    class Config:
        from_attributes = True


# ---------------------------------------------------------------------------
# Helper: Build RAG context string
# ---------------------------------------------------------------------------

def _build_rag_context(similar_feedbacks: List[dict]) -> Optional[str]:
    """
    Format similar feedbacks from RAG into a context string for Gemini.
    Returns None if no relevant feedbacks found.
    """
    if not similar_feedbacks:
        return None

    lines = []
    for i, item in enumerate(similar_feedbacks[:5], 1):
        text = item.get('text', '')[:150]
        sentiment = item.get('metadata', {}).get('sentiment', '?')
        lines.append(f"{i}. [{sentiment.upper()}] {text}")

    return "Similar past feedbacks:\n" + "\n".join(lines)


# ---------------------------------------------------------------------------
# CRUD Operations
# ---------------------------------------------------------------------------

@router.post("", response_model=FeedbackResponse, status_code=201)
async def create_feedback(
    feedback: FeedbackCreate,
    db: AsyncSession = Depends(get_db)
):
    """
    Create new feedback with AI analysis.

    Flow:
    1. RAG retrieves similar past feedbacks as context
    2. Gemini analyzes sentiment AND generates personalized sentiment_respon
       using the retrieved context — not a template
    3. Result is stored and indexed for future RAG queries
    """
    try:
        gemini = await get_gemini_service()
        rag = get_rag_pipeline()

        # Step 1: Retrieve similar feedbacks from RAG for context
        try:
            similar = rag.similarity_search(feedback.text, top_k=5)
            rag_context = _build_rag_context(similar)
        except Exception as e:
            logger.warning(f"⚠ RAG context retrieval failed: {str(e)}")
            rag_context = None

        # Step 2: Gemini analyzes sentiment + generates response using RAG context
        analysis = await gemini.analyze_feedback(feedback.text, rag_context=rag_context)

        new_feedback = Feedback(
            text=feedback.text,
            customer_id=feedback.customer_id,
            product_id=feedback.product_id,
            source=feedback.source,
            rating=feedback.rating,
            category=feedback.category,

            # Hasil dari Gemini
            sentiment=analysis.get('sentiment', 'neutral'),
            sentiment_respon=analysis.get('sentiment_respon', 'Terima kasih atas ulasan Anda.'),
        )

        db.add(new_feedback)
        await db.flush()

        # Step 3: Index new feedback into RAG
        rag.index_feedback(
            feedback_id=new_feedback.id,
            text=feedback.text,
            metadata={
                'sentiment':   new_feedback.sentiment,
                'category':    new_feedback.category,
                'source':      feedback.source,
                'customer_id': feedback.customer_id,
            }
        )

        await db.commit()
        await db.refresh(new_feedback)

        logger.info(
            f"✓ Created feedback {new_feedback.id} | "
            f"sentiment={new_feedback.sentiment} | "
            f"category={new_feedback.category} | "
            f"rag_context={'yes' if rag_context else 'no'}"
        )
        return new_feedback

    except Exception as e:
        await db.rollback()
        logger.error(f"❌ Error creating feedback: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/{feedback_id}", response_model=FeedbackResponse)
async def get_feedback(
    feedback_id: int,
    db: AsyncSession = Depends(get_db)
):
    """Get specific feedback by ID"""
    try:
        result = await db.execute(
            select(Feedback).where(Feedback.id == feedback_id)
        )
        feedback = result.scalar_one_or_none()
        if not feedback:
            raise HTTPException(status_code=404, detail="Feedback not found")
        return feedback
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error getting feedback: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("", response_model=List[FeedbackResponse])
async def list_feedbacks(
    skip: int = Query(0, ge=0),
    limit: int = Query(10, ge=1, le=100),
    sentiment: Optional[str] = None,
    category: Optional[str] = None,
    days: int = Query(7, ge=1),
    db: AsyncSession = Depends(get_db)
):
    """
    List feedbacks with filters.

    Query Parameters:
    - skip      : pagination offset
    - limit     : results per page (max 100)
    - sentiment : positive | neutral | negative
    - category  : kategori yang diisi user saat submit
    - days      : feedbacks from last N days (default 7)
    """
    try:
        query = select(Feedback)

        since = datetime.utcnow() - timedelta(days=days)
        query = query.where(Feedback.created_at >= since)

        if sentiment:
            try:
                sentiment_enum = SentimentType(sentiment)
                query = query.where(Feedback.sentiment == sentiment_enum)
            except ValueError:
                raise HTTPException(status_code=400, detail=f"Invalid sentiment: {sentiment}")

        if category:
            query = query.where(Feedback.category == category)

        query = query.order_by(desc(Feedback.created_at)).offset(skip).limit(limit)

        result = await db.execute(query)
        return result.scalars().all()

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error listing feedbacks: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))


@router.put("/{feedback_id}", response_model=FeedbackResponse)
async def update_feedback(
    feedback_id: int,
    update: FeedbackUpdate,
    db: AsyncSession = Depends(get_db)
):
    """Update feedback (manual override only)"""
    try:
        result = await db.execute(
            select(Feedback).where(Feedback.id == feedback_id)
        )
        feedback = result.scalar_one_or_none()
        if not feedback:
            raise HTTPException(status_code=404, detail="Feedback not found")

        if update.text:
            feedback.text = update.text
        if update.category:
            feedback.category = update.category
        if update.rating is not None:
            feedback.rating = update.rating
        if update.is_verified is not None:
            feedback.is_verified = update.is_verified

        feedback.updated_at = datetime.utcnow()

        await db.commit()
        await db.refresh(feedback)
        logger.info(f"✓ Updated feedback {feedback_id}")
        return feedback

    except HTTPException:
        raise
    except Exception as e:
        await db.rollback()
        logger.error(f"Error updating feedback: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))


@router.delete("/{feedback_id}", status_code=204)
async def delete_feedback(
    feedback_id: int,
    db: AsyncSession = Depends(get_db)
):
    """Delete feedback"""
    try:
        result = await db.execute(
            select(Feedback).where(Feedback.id == feedback_id)
        )
        feedback = result.scalar_one_or_none()
        if not feedback:
            raise HTTPException(status_code=404, detail="Feedback not found")

        rag = get_rag_pipeline()
        rag.delete_feedback(feedback_id)

        await db.delete(feedback)
        await db.commit()
        logger.info(f"✓ Deleted feedback {feedback_id}")

    except HTTPException:
        raise
    except Exception as e:
        await db.rollback()
        logger.error(f"Error deleting feedback: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))


# ---------------------------------------------------------------------------
# Search & Analytics
# ---------------------------------------------------------------------------

@router.get("/search", response_model=List[FeedbackResponse])
async def search_feedback(
    query: str = Query(..., min_length=1),
    top_k: int = Query(5, ge=1, le=20),
    db: AsyncSession = Depends(get_db)
):
    """Semantic search for similar feedbacks using RAG"""
    try:
        rag = get_rag_pipeline()
        results = rag.similarity_search(query, top_k=top_k)

        feedback_ids = [r['feedback_id'] for r in results]
        if not feedback_ids:
            return []

        query_stmt = select(Feedback).where(Feedback.id.in_(feedback_ids))
        result = await db.execute(query_stmt)
        feedbacks = result.scalars().all()

        feedback_dict = {f.id: f for f in feedbacks}
        return [feedback_dict[fid] for fid in feedback_ids if fid in feedback_dict]

    except Exception as e:
        logger.error(f"Error searching feedback: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/stats/summary")
async def feedback_summary(
    days: int = Query(7, ge=1),
    date: str = Query(None),
    db: AsyncSession = Depends(get_db)
):
    try:
        # kalau ada parameter date, filter spesifik tanggal itu aja
        if date:
            target_date = datetime.strptime(date, "%Y-%m-%d")
            since = target_date.replace(hour=0, minute=0, second=0)
            until = target_date.replace(hour=23, minute=59, second=59)
            date_filter = (Feedback.created_at >= since) & (Feedback.created_at <= until)
        else:
            since = datetime.utcnow() - timedelta(days=days)
            date_filter = Feedback.created_at >= since

        total_result = await db.execute(
            select(func.count(Feedback.id)).where(date_filter)
        )
        total = total_result.scalar()

        sentiment_result = await db.execute(
            select(Feedback.sentiment, func.count(Feedback.id))
            .where(date_filter)
            .group_by(Feedback.sentiment)
        )
        sentiment_counts = {row[0].value if hasattr(row[0], 'value') else row[0]: row[1]
                            for row in sentiment_result}

        category_result = await db.execute(
            select(Feedback.category, func.count(Feedback.id))
            .where(date_filter)
            .group_by(Feedback.category)
        )
        category_counts = {row[0] or 'other': row[1] for row in category_result}

        rating_result = await db.execute(
            select(func.avg(Feedback.rating)).where(
                date_filter,
                Feedback.rating.isnot(None)
            )
        )
        avg_rating = rating_result.scalar() or 0

        return {
            "period_days": 1 if date else days,
            "total_feedbacks": total,
            "sentiment_distribution": sentiment_counts,
            "category_distribution": category_counts,
            "average_rating": round(float(avg_rating), 2),
            "timestamp": datetime.utcnow().isoformat()
        }

    except Exception as e:
        logger.error(f"Error generating summary: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))


# ---------------------------------------------------------------------------
# Report endpoint — consumed by n8n for report generation
# ---------------------------------------------------------------------------

@router.get("/report/export")
async def export_report(
    days: int = Query(7, ge=1),
    date: str = Query(None),
    sentiment: Optional[str] = None,
    category: Optional[str] = None,
    db: AsyncSession = Depends(get_db)
):
    """
    Export feedback report untuk n8n pipeline.

    Returns flat list dengan:
    - id, customer_id, rating, text
    - sentiment, sentiment_respon
    - category, source, created_at
    """
    try:
        if date:
            target_date = datetime.strptime(date, "%Y-%m-%d")
            since = target_date.replace(hour=0, minute=0, second=0)
            until = target_date.replace(hour=23, minute=59, second=59)
            date_filter = (Feedback.created_at >= since) & (Feedback.created_at <= until)
        else:
            since = datetime.utcnow() - timedelta(days=days)
            date_filter = Feedback.created_at >= since

        query = select(Feedback).where(date_filter)

        if sentiment:
            query = query.where(Feedback.sentiment == sentiment)
        if category:
            query = query.where(Feedback.category == category)

        query = query.order_by(desc(Feedback.created_at))
        result = await db.execute(query)
        feedbacks = result.scalars().all()

        rows = []
        for f in feedbacks:
            rows.append({
                "id": f.id,
                "customer_id": f.customer_id or "-",
                "product_id": f.product_id or "-",
                "rating": f.rating,
                "text": f.text,
                "sentiment": f.sentiment.value if hasattr(f.sentiment, 'value') else f.sentiment,
                "sentiment_respon": f.sentiment_respon or "-",
                "category": f.category or "-",
                "source": f.source or "-",
                "created_at": f.created_at.isoformat() if f.created_at else "-",
            })

        return {
            "period_days": 1 if date else days,
            "total": len(rows),
            "generated_at": datetime.utcnow().isoformat(),
            "feedbacks": rows
        }

    except Exception as e:
        logger.error(f"Error exporting report: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))